export const PPT_THEMES = [
  {
    id: "corporate_blue",
    name: "Corporate Blue",
    layout: "framed",
    bg: "bg-gradient-to-br from-slate-50 via-slate-100 to-slate-200",
    accent: "bg-blue-700",
    title: "text-[44px] leading-tight font-bold tracking-tight text-slate-900",
    bullet: "text-slate-800",
    frame: "bg-white/85 border-slate-300/70",
    dot: "text-blue-700",
    footer: "text-slate-600",
  },
  {
    id: "corporate_gray",
    name: "Corporate Gray",
    layout: "band_top",
    bg: "bg-gradient-to-br from-zinc-100 via-zinc-200 to-zinc-300",
    accent: "bg-zinc-800",
    title: "text-[42px] leading-tight font-bold tracking-tight text-zinc-950",
    bullet: "text-zinc-800",
    frame: "bg-white/85 border-zinc-300/70",
    dot: "text-zinc-800",
    footer: "text-zinc-600",
  },
  {
    id: "corporate_purple",
    name: "Corporate Purple",
    layout: "split_left",
    bg: "bg-gradient-to-br from-violet-50 via-purple-100 to-fuchsia-200",
    accent: "bg-violet-700",
    title: "text-[42px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-violet-950",
    frame: "bg-white/75 border-violet-300/70",
    dot: "text-violet-700",
    footer: "text-violet-800/80",
  },
  {
    id: "academic_white",
    name: "Academic White",
    layout: "minimal_grid",
    bg: "bg-gradient-to-br from-white to-slate-100",
    accent: "bg-blue-900",
    title: "text-[42px] leading-tight font-semibold tracking-tight text-slate-900",
    bullet: "text-slate-900",
    frame: "bg-white border-slate-200",
    dot: "text-blue-900",
    footer: "text-slate-600",
  },
  {
    id: "academic_beige",
    name: "Academic Beige",
    layout: "sidebar_right",
    bg: "bg-gradient-to-br from-[#f8f5f0] to-[#ece6db]",
    accent: "bg-[#4b5563]",
    title: "text-[40px] leading-tight font-semibold tracking-tight text-white",
    bullet: "text-[#374151]",
    frame: "bg-white/70 border-[#c7b8a1]",
    dot: "text-[#4b5563]",
    footer: "text-[#5f6670]",
  },
  {
    id: "ai_gradient",
    name: "AI Gradient",
    layout: "mesh",
    bg: "bg-gradient-to-br from-[#5b21b6] via-[#2563eb] to-[#06b6d4]",
    accent: "bg-white/70",
    title: "text-[44px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-cyan-50",
    frame: "bg-black/20 border-white/20",
    dot: "text-cyan-200",
    footer: "text-cyan-100/80",
  },
  {
    id: "neon_dark",
    name: "Neon Dark",
    layout: "darkboard",
    bg: "bg-gradient-to-br from-[#090f1f] via-[#0f172a] to-[#0b1220]",
    accent: "bg-cyan-400",
    title: "text-[44px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-slate-200",
    frame: "bg-white/[0.04] border-cyan-400/30",
    dot: "text-cyan-300",
    footer: "text-slate-400",
  },
  {
    id: "startup_minimal",
    name: "Startup Minimal",
    layout: "cards",
    bg: "bg-gradient-to-br from-white to-zinc-100",
    accent: "bg-black",
    title: "text-[42px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-zinc-700",
    frame: "bg-white border-zinc-300/80",
    dot: "text-zinc-900",
    footer: "text-zinc-500",
  },
  {
    id: "startup_dark",
    name: "Startup Dark",
    layout: "spotlight",
    bg: "bg-gradient-to-br from-[#111827] via-[#1f2937] to-[#0f172a]",
    accent: "bg-indigo-500",
    title: "text-[44px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-slate-200",
    frame: "bg-white/[0.04] border-indigo-300/25",
    dot: "text-indigo-300",
    footer: "text-slate-400",
  },
  {
    id: "sunset",
    name: "Sunset",
    layout: "diagonal",
    bg: "bg-gradient-to-br from-orange-500 via-rose-500 to-fuchsia-600",
    accent: "bg-white/30",
    title: "text-[44px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-orange-50",
    frame: "bg-black/20 border-white/25",
    dot: "text-amber-100",
    footer: "text-orange-100/85",
  },
  {
    id: "forest",
    name: "Forest",
    layout: "pillar",
    bg: "bg-gradient-to-br from-emerald-700 via-green-700 to-teal-900",
    accent: "bg-lime-400",
    title: "text-[42px] leading-tight font-bold tracking-tight text-white",
    bullet: "text-emerald-50",
    frame: "bg-black/20 border-lime-300/35",
    dot: "text-lime-300",
    footer: "text-emerald-100/80",
  },
  {
    id: "neural_pulse",
    name: "Neural Pulse",
    bg: "bg-[radial-gradient(circle_at_top,_#1e1b4b,_#020617)]",
    accent: "bg-indigo-400 shadow-[0_0_30px_rgba(129,140,248,0.9)]",
    title: "text-4xl font-extrabold text-indigo-300 tracking-tight drop-shadow-[0_0_25px_rgba(129,140,248,0.8)]",
    bullet: "text-slate-300",
  },
  {
    id: "stellar_grid",
    name: "Stellar Grid",
    bg: "bg-[linear-gradient(135deg,_#020617_25%,_#020617_50%,_#020617_75%)] bg-[length:40px_40px]",
    accent: "bg-cyan-300 shadow-[0_0_25px_rgba(34,211,238,0.8)]",
    title: "text-4xl font-bold text-cyan-200 drop-shadow-[0_0_18px_rgba(34,211,238,0.7)]",
    bullet: "text-slate-400",
  },
  {
    id: "dna_spectrum",
    name: "DNA Spectrum",
    bg: "bg-gradient-to-br from-emerald-950 via-indigo-950 to-rose-950",
    accent: "bg-gradient-to-r from-emerald-400 to-rose-400 shadow-[0_0_30px_rgba(110,231,183,0.8)]",
    title: "text-4xl font-extrabold text-transparent bg-clip-text bg-gradient-to-r from-emerald-300 to-rose-300",
    bullet: "text-slate-200",
  },
  {
    id: "deep_space_void",
    name: "Deep Space Void",
    bg: "bg-black",
    accent: "bg-white/10 backdrop-blur-md border border-white/20",
    title: "text-4xl font-semibold text-white tracking-tight",
    bullet: "text-slate-400",
  },
  {
    id: "noir_silicon",
    name: "Noir Silicon",
    bg: "bg-gradient-to-br from-zinc-950 via-zinc-900 to-neutral-900",
    accent: "bg-amber-400 shadow-[0_0_20px_rgba(251,191,36,0.8)]",
    title: "text-4xl font-bold text-amber-300 tracking-tight",
    bullet: "text-zinc-300",
  },
  {
    id: "quantum_bloom",
    name: "Quantum Bloom",
    bg: "bg-gradient-to-br from-yellow-200 via-fuchsia-300 to-indigo-400",
    accent: "bg-black shadow-[0_0_20px_rgba(0,0,0,0.4)]",
    title: "text-4xl font-black text-black tracking-tight",
    bullet: "text-slate-900",
  },
  {
    id: "prismatic_flux",
    name: "Prismatic Flux",
    bg: "bg-[conic-gradient(from_180deg,_#22d3ee,_#a78bfa,_#f472b6,_#22d3ee)]",
    accent: "bg-white shadow-[0_0_25px_rgba(255,255,255,0.9)]",
    title: "text-4xl font-extrabold text-white drop-shadow-[0_0_20px_rgba(0,0,0,0.6)]",
    bullet: "text-white/90",
  },
  {
    id: "ai_research_lab",
    name: "AI Research Lab",
    bg: "bg-gradient-to-br from-slate-100 via-slate-200 to-slate-300",
    accent: "bg-indigo-600",
    title: "text-4xl font-semibold text-slate-900 tracking-tight",
    bullet: "text-slate-700",
  },
  {
    id: "holographic_matrix",
    name: "Holographic Matrix",
    bg: "bg-[linear-gradient(120deg,_#020617,_#1e1b4b,_#020617)]",
    accent: "bg-cyan-300 shadow-[0_0_35px_rgba(103,232,249,0.9)]",
    title: "text-4xl font-extrabold text-cyan-200 drop-shadow-[0_0_30px_rgba(103,232,249,0.8)]",
    bullet: "text-slate-300",
  },
  {
    id: "obsidian_gold",
    name: "Obsidian Gold",
    bg: "bg-gradient-to-br from-black via-zinc-900 to-black",
    accent: "bg-yellow-400 shadow-[0_0_35px_rgba(250,204,21,1)]",
    title: "text-4xl font-extrabold text-yellow-300 tracking-tight",
    bullet: "text-zinc-300",
  },
  {
    id: "frosted_ai",
    name: "Frosted AI",
    bg: "bg-gradient-to-br from-white/10 via-slate-200/20 to-white/10 backdrop-blur-2xl",
    accent: "bg-white/30 border border-white/40",
    title: "text-4xl font-semibold text-white tracking-tight",
    bullet: "text-white/80",
  },
  {
    id: "liquid_glass_dark",
    name: "Liquid Glass Dark",
    bg: "bg-gradient-to-br from-slate-950 via-slate-900 to-black",
    accent: "bg-white/10 backdrop-blur-xl border border-white/20",
    title: "text-4xl font-semibold text-white tracking-tight",
    bullet: "text-slate-400",
  },
  {
    id: "bio_luminescence",
    name: "Bio Luminescence",
    bg: "bg-gradient-to-br from-emerald-900 via-cyan-900 to-blue-950",
    accent: "bg-emerald-300 shadow-[0_0_30px_rgba(110,231,183,0.9)]",
    title: "text-4xl font-extrabold text-emerald-200 drop-shadow-[0_0_22px_rgba(110,231,183,0.8)]",
    bullet: "text-slate-200",
  },
  {
    id: "genome_wave",
    name: "Genome Wave",
    bg: "bg-gradient-to-br from-indigo-950 via-fuchsia-950 to-rose-950",
    accent: "bg-fuchsia-400 shadow-[0_0_30px_rgba(232,121,249,0.9)]",
    title: "text-4xl font-extrabold text-fuchsia-300 drop-shadow-[0_0_22px_rgba(232,121,249,0.8)]",
    bullet: "text-slate-300",
  },
  {
    id: "terminal_ai",
    name: "Terminal AI",
    bg: "bg-black",
    accent: "bg-green-500 shadow-[0_0_25px_rgba(34,197,94,0.9)]",
    title: "text-4xl font-mono font-bold text-green-400",
    bullet: "text-green-300 font-mono",
  },
  {
    id: "code_void",
    name: "Code Void",
    bg: "bg-gradient-to-br from-black via-neutral-950 to-black",
    accent: "bg-indigo-500 shadow-[0_0_25px_rgba(99,102,241,0.9)]",
    title: "text-4xl font-mono font-bold text-indigo-300",
    bullet: "text-slate-400 font-mono",
  },
  {
    id: "frozen_hologram",
    name: "Frozen Hologram",
    bg: "bg-gradient-to-br from-cyan-200/20 via-blue-300/20 to-indigo-400/20 backdrop-blur-2xl",
    accent: "bg-cyan-300/50 shadow-[0_0_30px_rgba(103,232,249,0.9)]",
    title: "text-4xl font-extrabold text-white drop-shadow-[0_0_20px_rgba(103,232,249,0.8)]",
    bullet: "text-white/80",
  },
  {
    id: "aurora_liquid",
    name: "Aurora Liquid",
    bg: "bg-gradient-to-br from-teal-400 via-cyan-500 to-indigo-600",
    accent: "bg-white shadow-[0_0_20px_rgba(255,255,255,0.8)]",
    title: "text-4xl font-extrabold text-white drop-shadow-[0_0_18px_rgba(0,0,0,0.6)]",
    bullet: "text-white/90",
  },
  {
    id: "cosmic_rift",
    name: "Cosmic Rift",
    bg: "bg-[radial-gradient(circle_at_center,_#312e81,_#020617)]",
    accent: "bg-indigo-500 shadow-[0_0_35px_rgba(99,102,241,0.9)]",
    title: "text-4xl font-extrabold text-indigo-300 drop-shadow-[0_0_25px_rgba(99,102,241,0.8)]",
    bullet: "text-slate-300",
  },
  {
    id: "platinum_future",
    name: "Platinum Future",
    bg: "bg-gradient-to-br from-slate-200 via-slate-300 to-slate-400",
    accent: "bg-slate-900",
    title: "text-4xl font-semibold text-slate-900 tracking-tight",
    bullet: "text-slate-700",
  },
];
